[book]
authors = ["parksb"]
language = "en"
multilingual = false
src = "src"
title = "Zap Documentation"

[output.html]
curly-quotes = true
git-repository-url = "https://github.com/zap-lib/zap-lib.github.io"
additional-css = ["src/styles.css"]
